### ISSUE TITLE
doc: Update docs/tutorials/deploy-vm/README.md

### ISSUE THREAD

**Issue by akutz** [vmware-tanzu/vm-operator#121]
This ticket tracks updating [`./docs/tutorials/deploy-vm/README.md`](https://github.com/vmware-tanzu/vm-operator/tree/main/docs/tutorials/deploy-vm/README.md). Please refer to https://vm-operator.rtfd.io/en/latest/ref/proj/docs/#project-docs for guidelines on writing VM Operator project documentation.

**Comment by zyiyi11** [comment]
https://github.com/vmware-tanzu/vm-operator/pull/183 solved this issue.
