### ISSUE TITLE
Only perform template substitutions for bootstrap type vAppConfig

### ISSUE THREAD

**Issue by aruneshpa** [vmware-tanzu/vm-operator#146]
**What steps did you take and what happened?**

VM operator can accept Golang template strings in bootstrap user-data and perform any substitutions before passing it down to the guest.  However, as of today, the only bootstrap method that supports templating is `vAppConfig`.  This should be enforced in code.

This can cause issues in situations where users want to send cloud-config user-data to the guest using the `CloudInit` boostrap type.  If the user-data contains any template markers (e.g., `{{`), the current code will try to evaluate that -- which can result in inconsistent and unwarranted behavior.  

Often times, guests use Jinja templating in cloud-config user-data where we want markers to be replaced by the instance metadata file in guest during cloud-init.
For example, the following snippet from the[ cloud-init docs](https://cloudinit.readthedocs.io/en/22.4.1/topics/instancedata.html) demonstrates using Jinja templating to replace the hostname of the EC2 instance type:
```
## template: jinja
#cloud-config
runcmd:
    - echo 'EC2 public hostname allocated to instance: {{
      ds.meta_data.public_hostname }}' > /tmp/instance_metadata
    - echo 'EC2 availability zone: {{ v1.availability_zone }}' >>
      /tmp/instance_metadata
    - curl -X POST -d '{"hostname": "{{ds.meta_data.public_hostname }}",
      "availability-zone": "{{ v1.availability_zone }}"}'
      https://example.com
```

With this bug, VM operator will try to evaluate the `{{ ds.meta_data.public_hostname }}` and emit an error.  This will cause confusion for users.

**What did you expect to happen?**

For any other bootstrap type except `vAppConfig`, templating in bootstrap data should not be performed.
More specifically, the following code should be modified to only perform template substitutions when the bootstrap type is `vAppConfig`:
https://github.com/vmware-tanzu/vm-operator/blob/4c4f22a0bcb0ce67aa91cbfc9b4dd5360b8cdb11/pkg/vmprovider/providers/vsphere/session/session_vm_customization.go#L256

**Is there anything else you would like to add?**

N/A

**Please tell us about your environment.**

This issue has existed as far as I can go back in the history of VM operator.

**Comment by dilyar85** [comment]
> However, as of today, the only bootstrap method that supports templating is `vAppConfig`.

`Sysprep` also uses templating expressions to specify required network settings (e.g. MAC and IP addresses). See [this answer file](https://vm-operator.readthedocs.io/en/latest/concepts/workloads/guest/#minimal-config) for an example of its usage.
