### ISSUE TITLE
Prevent user from setting FirstBootDoneAnnotation

### ISSUE THREAD

**Issue by zyiyi11** [vmware-tanzu/vm-operator#221]
**Please describe the solution you would like.**
Add a webhook validation to prevent users from setting `FirstBootDoneAnnotation`. Utilize `IsPrivilegedAccount` to determine if they are an SSO user. If they are, reject attempts to modify that annotation. 

**Is there anything else you would like to add?**
N/A
**Please tell us about your environment.**
N/A

**Comment by dilyar85** [comment]
@zyiyi11 Should we close this as https://github.com/vmware-tanzu/vm-operator/pull/211 is merged?

**Comment by zyiyi11** [comment]
No, #211 only prevented user from setting `cloud-init-instance-id` annotation. This one is for `first-boot-done`
